"""Initial SIMPA schema.

Revision ID: 001
Revises: 
Create Date: 2026-03-03 03:00:00.000000

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create pgvector extension first
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refined_prompts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=False),
        sa.Column('main_language', sa.String(length=50), nullable=False),
        sa.Column('other_languages', sa.JSON(), nullable=True),
        sa.Column('agent_type', sa.String(length=100), nullable=False),
        sa.Column('original_prompt', sa.Text(), nullable=False),
        sa.Column('refined_prompt', sa.Text(), nullable=False),
        sa.Column('prior_refinement_id', sa.UUID(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=False),
        sa.Column('average_score', sa.Float(), nullable=False),
        sa.Column('score_distribution', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['prior_refinement_id'], ['refined_prompts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refined_prompts_agent_type'), 'refined_prompts', ['agent_type'], unique=False)
    op.create_index(op.f('ix_refined_prompts_main_language'), 'refined_prompts', ['main_language'], unique=False)
    
    # Create IVFFlat index for vector similarity search
    # Using lists=100 as a reasonable default for expected data volume
    op.execute("CREATE INDEX ON refined_prompts USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")
    
    op.create_table('prompt_history',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('refined_prompt_id', sa.UUID(), nullable=False),
        sa.Column('action_score', sa.Float(), nullable=False),
        sa.Column('validation_results', sa.JSON(), nullable=True),
        sa.Column('files_modified', sa.JSON(), nullable=True),
        sa.Column('diffs_by_language', sa.JSON(), nullable=True),
        sa.Column('request_context', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['refined_prompt_id'], ['refined_prompts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_history_refined_prompt_id'), 'prompt_history', ['refined_prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop vector index first
    op.execute("DROP INDEX IF EXISTS refined_prompts_embedding_idx")
    
    op.drop_index(op.f('ix_prompt_history_refined_prompt_id'), table_name='prompt_history')
    op.drop_table('prompt_history')
    op.drop_index(op.f('ix_refined_prompts_main_language'), table_name='refined_prompts')
    op.drop_index(op.f('ix_refined_prompts_agent_type'), table_name='refined_prompts')
    op.drop_table('refined_prompts')
    # ### end Alembic commands ###
