"""Initial SIMPA schema.

Revision ID: 001
Revises: 
Create Date: 2026-03-03 03:00:00.000000

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create pgvector extension first
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refined_prompts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('prompt_key', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
        sa.Column('agent_type', sa.String(length=100), nullable=False),
        sa.Column('main_language', sa.String(length=50), nullable=True),
        sa.Column('other_languages', sa.JSON(), nullable=True),
        sa.Column('domain', sa.String(length=100), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('original_prompt_hash', sa.String(length=64), nullable=True),
        sa.Column('original_prompt', sa.Text(), nullable=False),
        sa.Column('refined_prompt', sa.Text(), nullable=False),
        sa.Column('refinement_version', sa.Integer(), nullable=False, server_default=sa.text('1')),
        sa.Column('prior_refinement_id', sa.UUID(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('average_score', sa.Float(), nullable=False, server_default=sa.text('0')),
        sa.Column('score_weighted', sa.Float(), nullable=False, server_default=sa.text('0')),
        sa.Column('score_dist_1', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('score_dist_2', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('score_dist_3', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('score_dist_4', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('score_dist_5', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.ForeignKeyConstraint(['prior_refinement_id'], ['refined_prompts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('prompt_key')
    )
    op.create_index(op.f('ix_refined_prompts_agent_type'), 'refined_prompts', ['agent_type'], unique=False)
    op.create_index(op.f('ix_refined_prompts_main_language'), 'refined_prompts', ['main_language'], unique=False)
    
    # Create IVFFlat index for vector similarity search
    # Using lists=100 as a reasonable default for expected data volume
    op.execute("CREATE INDEX ON refined_prompts USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")
    
    op.create_table('prompt_history',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('prompt_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('request_id', sa.UUID(), nullable=True),
        sa.Column('executed_by_agent', sa.String(length=100), nullable=True),
        sa.Column('action_score', sa.Float(), nullable=False),
        sa.Column('test_passed', sa.Boolean(), nullable=True),
        sa.Column('lint_score', sa.Float(), nullable=True),
        sa.Column('security_scan_passed', sa.Boolean(), nullable=True),
        sa.Column('files_modified', sa.JSON(), nullable=True),
        sa.Column('files_added', sa.JSON(), nullable=True),
        sa.Column('files_deleted', sa.JSON(), nullable=True),
        sa.Column('diffs', sa.JSON(), nullable=True),
        sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
        sa.Column('agent_output_summary', sa.Text(), nullable=True),
        sa.Column('validation_results', sa.JSON(), nullable=True),
        sa.Column('saliency_metadata', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['prompt_id'], ['refined_prompts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_history_refined_prompt_id'), 'prompt_history', ['refined_prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop vector index first
    op.execute("DROP INDEX IF EXISTS refined_prompts_embedding_idx")
    
    op.drop_index(op.f('ix_prompt_history_refined_prompt_id'), table_name='prompt_history')
    op.drop_table('prompt_history')
    op.drop_index(op.f('ix_refined_prompts_main_language'), table_name='refined_prompts')
    op.drop_index(op.f('ix_refined_prompts_agent_type'), table_name='refined_prompts')
    op.drop_table('refined_prompts')
    # ### end Alembic commands ###
